/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateSessionRouteImport } from './routes/create-session'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as NetNetIdRouteImport } from './routes/net.$netId'
import { Route as SimulateNetIdRouteImport } from './routes/simulate.$netId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateSessionRoute = CreateSessionRouteImport.update({
  id: '/create-session',
  path: '/create-session',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const NetNetIdRoute = NetNetIdRouteImport.update({
  id: '/net/$netId',
  path: '/net/$netId',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulateNetIdRoute = SimulateNetIdRouteImport.update({
  id: '/simulate/$netId',
  path: '/simulate/$netId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-session': typeof CreateSessionRoute
  '/sessions': typeof SessionsRoute
  '/net/$netId': typeof NetNetIdRoute
  '/simulate/$netId': typeof SimulateNetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-session': typeof CreateSessionRoute
  '/sessions': typeof SessionsRoute
  '/net/$netId': typeof NetNetIdRoute
  '/simulate/$netId': typeof SimulateNetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-session': typeof CreateSessionRoute
  '/sessions': typeof SessionsRoute
  '/net/$netId': typeof NetNetIdRoute
  '/simulate/$netId': typeof SimulateNetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/create-session' | '/sessions' | '/net/$netId' | '/simulate/$netId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-session' | '/sessions' | '/net/$netId' | '/simulate/$netId'
  id:
    | '__root__'
    | '/'
    | '/create-session'
    | '/sessions'
    | '/net/$netId'
    | '/simulate/$netId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateSessionRoute: typeof CreateSessionRoute
  SessionsRoute: typeof SessionsRoute
  NetNetIdRoute: typeof NetNetIdRoute
  SimulateNetIdRoute: typeof SimulateNetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-session': {
      id: '/create-session'
      path: '/create-session'
      fullPath: '/create-session'
      preLoaderRoute: typeof CreateSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/net/$netId': {
      id: '/net/$netId'
      path: '/net/$netId'
      fullPath: '/net/$netId'
      preLoaderRoute: typeof NetNetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulate/$netId': {
      id: '/simulate/$netId'
      path: '/simulate/$netId'
      fullPath: '/simulate/$netId'
      preLoaderRoute: typeof SimulateNetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateSessionRoute: CreateSessionRoute,
  SessionsRoute: SessionsRoute,
  NetNetIdRoute: NetNetIdRoute,
  SimulateNetIdRoute: SimulateNetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
